name: sector-coupled-euro-calliope
channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.7
    - flake8
    - numpy=1.18.5
    - pandas=1.0.5
    - gdal=3.0.4
    - matplotlib=3.2.2
    - pillow=7.1.2
    - seaborn=0.10.1
    - click=7.1.2
    - ipython=7.15.0
    - fiona=1.8.13
    - rasterio=1.1.5
    - rasterstats=0.14.0
    - geopandas=0.8.0
    - pycountry=19.8.18
    - xlrd=1.2.0
    - descartes=1.1.0
    - xarray=0.15.1
    - netcdf4=1.5.3
    - pyyaml=5.3.1
    - pip=19.1.1
    - snakemake-minimal=6.15.5
