__default__:
    runtime: 60
    cores: 1
    memory: 16000
    scratch: 100
    output: "build/logs/{rule}.{wildcards}.log"
    name: "{rule}.{wildcards}"
run_continental:
    runtime: 5
    memory: 1000
run_national:
    runtime: 60
    cores: 6
    memory: 6000
aggregated_results:
    runtime: 60
xy:
    runtime: 60
test:
    runtime: 60
uncertainty_analysis:
    runtime: 120
input_netcdf:
    runtime: 240
    memory: 40000
    cores: 4
run_eurocalliope:
    runtime: 1440
    cores: 6
    memory: 100000
    scratch: 4000
build_eurocalliope:
    runtime: 480
    memory: 100000
heat_demand_profiles:
    runtime: 100
    memory: 80000
spores_result_metrics:
    memory: 30000
    runtime: 120
consolidate_scenario_results:
    memory: 40000
    runtime: 120
results_to_iamc_friendly:
    memory: 20000
    runtime: 60
results_to_friendly:
    memory: 30000
    runtime: 60
results_to_friendly_spores:
    memory: 100000
    runtime: 240
cost_opt_result_metrics:
    memory: 100000
    runtime: 240
consolidate_cost_opt_metrics:
    memory: 60000
    runtime: 240
inflow_m3:
    runtime: 100
inflow_mwh:
    runtime: 100
    memory: 40000
capacity_factors_hydro:
    runtime: 100
capacity_factors_offshore:
    runtime: 30
capacity_factors_onshore_wind_and_solar:
    runtime: 30
    memory: 30000
download_runoff_data:
    runtime: 240
