overrides:
    config_overrides:
            techs:
                solar_thermal_collector.exists: false  # TODO: create ST timeseries to allow these techs to exist
                solar_thermal_energy.exists: false  # TODO: create ST timeseries to allow these techs to exist
                ashp.exists: false
                gshp.exists: false
                demand_space_heat.exists: false
                demand_water_heat.exists: false
                ashp_heat_storage_small.exists: false
                ashp_tech_heat_to_demand.exists: false
                gshp_heat_storage_small.exists: false
                gshp_tech_heat_to_demand.exists: false
                hydrogen_electricity_storage.exists: false
                biogas_to_electricity_supply.exists: false
